<?php

namespace FondOfSpryker\Yves\GoogleTagManagerOrderConnector;

use Spryker\Yves\Kernel\AbstractBundleDependencyProvider;
use Spryker\Yves\Kernel\Container;

class GoogleTagManagerOrderConnectorDependencyProvider extends AbstractBundleDependencyProvider
{
    public function provideDependencies(Container $container)
    {
        return parent::provideDependencies($container); // TODO: Change the autogenerated stub
    }
}
